mo271/klein

- js/data/teilnehmer.json
- js/teilnehmer.js
> sort teilnehmer by last name

- js/data/protokolle.json
... since it is moved to teilnehmer.json and let's not keep duplicate information around. Fixes #1.
> remove name field from protokolle.json

- js/data/protokolle.json
- js/data/teilnehmer.json
Name from here:
https://digicoll.library.wisc.edu/cgi/f/findaid/findaid-idx?c=wiarchives;cc=wiarchives;view=text;rgn=main;didno=uw-whs-lx000a
> merge Comstock

- js/data/protokolle.json
- js/data/teilnehmer.json
> merge Zurhellen

- js/data/teilnehmer.json
Hat nichts mit H. Duncker zu tun
> Johannes Denker aus Celle

- js/data/protokolle.json
- js/data/teilnehmer.json
Ich hab das mit jupyter leider nicht hinbekommen. Da Merges aber nicht so häufig vorkommen wäre es für mich auch ok das händisch zu machen
> Furtwängler, Seitenzahlen anpassen & Merge

- js/data/teilnehmer.json
Im Verzeichnis gibt es nur diesen einen Goldman oder Goldmann in diesem Semester. Wo kommt der Name "Max" her? In den Protokollen habe ich keinen Vornamen gefunden.
> Meier[?] Goldman aus Lodz, Rußl[and].

- js/data/teilnehmer.json
TO 2021 = Tobies, Klein-Biographie, engl. Ausgabe von 2021 (2025 soll eine überarbeitete deutsche Ausgabe erscheinen)
> Heinrich Hoppe aus Chemnitz

- js/teilnehmer.js
Fixes #82
See for example https://firsching.ch/klein/teilnehmer/#id-664
> display name_non_latin

- js/teilnehmer.js
> expose origin field

- js/klein.js
- js/teilnehmer.js
> abbreviate Wochentag

- js/data/protokolle.json
- js/data/teilnehmer.json
Bei den 4 Lauberts müsste es sich um dieselbe Person handeln. Ich habe in allen Quellen geschaut und nur einen "H. Laubert" bzw. "Heinrich Laubert" gefunden der mehrere Semester ununterbrochen in Göttingen war. Handschriften stimmen für mich auch überein, aber vielleicht willst du noch einmal schauen?
> verschiedene Merges

- js/teilnehmer.js
> allow filtering by band/seminar in teilnehmer

- .github/workflows/mirror_to_parent.yml
> only run deploy on mo271/klein

- js/data/teilnehmer.json
Der Vortragende ist sicher nicht Robert Fricke (Handshcrift), und höchstwahrscheinlich Hermann Fricke aus Goslar. Ich glaube ich habe irgendwo mal einen Abdruck dieses Vortrages gesehen mit dem falschen Hinweis dass er von Robert Fricke komme.
> Hermann Fricke

- js/data/teilnehmer.json
- js/klein.js
using capital Kappa and Alpha as a hack to sort 121 and 931 at the right place.
> fix sorting

- js/data/teilnehmer.json
Renate Tobies:
Mittwoch, 1.VI.1904
Die [Thomas] Bayessche Regel.
[Jerimias?] Grossmann
Band 20, Seite 197
> August Grossmann

- js/data/teilnehmer.json
Renate Tobies:
Ws 1897/98 Habe diesen zufaellig gefunden: Walley, J. H. Gloucester, England
> source and origin for J.H. Walley

- js/data/protokolle.json
- js/data/teilnehmer.json
- scripts/integrity.py
> Integrity check for protokolle

- js/klein.js
#292 should work now, waiting for a first example..
> display sns

- js/data/teilnehmer.json
Neue Updates unter altem Namen
> Johnson und andere

- js/data/protokolle.json
- js/data/teilnehmer.json
> merge zorn

- js/data/teilnehmer.json
Newkirk hat sich selbst als "Neukirch" inskribiert :D
> einige updates.

- js/klein.js
> add navigation for extra pages

- map/decimaldate.js
- map/index.html
- map/leaflet-ohm-timeslider.css
- map/leaflet-ohm-timeslider.js
- map/mapstyle.js
> use historical map

- js/data/teilnehmer.json
> fix some locations,

- js/klein.js
- map/index.html
> link to map

- js/data/teilnehmer.json
> rulf neuer link inkl Lebensdaten
